### ISSUE TITLE
error in instalation module farm in odoo 10

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [OCA/vertical-agriculture#5]
`Traceback (most recent call last):
  File "/vagrant/odoo/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/vagrant/odoo/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/vagrant/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/vagrant/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/vagrant/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/vagrant/odoo/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/vagrant/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/vagrant/odoo/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/vagrant/odoo/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/vagrant/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/vagrant/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/vagrant/odoo/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/vagrant/odoo/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/vagrant/odoo/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/vagrant/odoo/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/vagrant/odoo/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/vagrant/odoo/odoo/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/vagrant/odoo/odoo/odoo/modules/registry.py", line 314, in init_models
    model.init()
TypeError: init() takes exactly 2 arguments (1 given)`

**Comment by pedrobaeza** [comment]
Module is not available in that version.

**Comment by luizcarlospedrosogomes** [comment]
can I migrate it to version 10 using: https: //github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by pedrobaeza** [comment]
You have to do more than the things in that guide. You require to know how to program in Odoo.

**Comment by luizcarlospedrosogomes** [comment]
do you have any prediction of when this module will be available for version 10?

**Comment by luizcarlospedrosogomes** [comment]
one last doubt Do you know any other module for farms?

**Comment by pedrobaeza** [comment]
No for both.
