### ISSUE TITLE
error instalation odoo 8

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [OCA/vertical-agriculture#6]
`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/wizard/base_module_upgrade.py", line 105, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/opt/odoo/openerp/modules/registry.py", line 197, in setup_models
    model._setup_complete(cr, SUPERUSER_ID)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3032, in _setup_complete
    field.setup_triggers(self.env)
  File "/opt/odoo/openerp/fields.py", line 1743, in setup_triggers
    self._setup_dependency([self.name], comodel, arg[0].split('.'))
  File "/opt/odoo/openerp/fields.py", line 624, in _setup_dependency
    fields = [model._fields[head]]
KeyError: 'usage'`

**Comment by luizcarlospedrosogomes** [comment]
alguem?

**Comment by luizcarlospedrosogomes** [comment]
@pedrobaeza help-me

**Comment by pedrobaeza** [comment]
Sorry, but nobody has migrated any module in any version for this vertical, so it's normal that there are errors. I don't know even where do you have taken any code.

**Comment by luizcarlospedrosogomes** [comment]
@pedrobaeza  error in instalation **odoo 8** . tanks

https://www.odoo.com/apps/modules/8.0/farm/

**Comment by pedrobaeza** [comment]
That module is not hosted here.

**Comment by luizcarlospedrosogomes** [comment]
![image](https://user-images.githubusercontent.com/9791364/31564285-a7a53ac4-b038-11e7-94c1-63bf5338fb64.png)


![image](https://user-images.githubusercontent.com/9791364/31564031-d4cf4630-b037-11e7-8c0d-e681af3c424c.png)

for link redirect for here

**Comment by pedrobaeza** [comment]
Well, as said, it's not hosted here. Thank link is wrong. Maybe @acysos can specify.
